[package]
name = "benches"
version = "0.1.0"
edition = "2021"

[dependencies]
ndarray = { version = "0.15.0", features = ["blas"] }
ndarray-rand = "0.14.0"
blas-src = { version = "0.8", features = ["openblas"] }
openblas-src = { version = "0.10", features = ["cblas", "system"] }